### ISSUE TITLE
Maybe a typo

### ISSUE THREAD

**Issue by codeworm96** [gaocegege/scala-renren#1]
The 'paly' in the brief description is confusing. Is it a typo?

**Comment by hczhcz** [comment]
Wnorg speillng oredr is not cofnuisng in Egnilsh. Dno't wrroy XD.

**Comment by gaocegege** [comment]
@codeworm96  ....peopel can konw what i want to sya.😄ahah

**Comment by codeworm96** [comment]
@gaocegege @hczhcz Yes. It's not a big error. But it is better to fix the spelling mistake.

**Comment by hczhcz** [comment]
@codeworm96 just joking =w=

**Comment by gaocegege** [comment]
@codeworm96 😄Of course, fixed
